---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: "kube-state-metrics-{{ .name }}"
    spec:
      # TODO make a real project
      project: default
      sources:
        - repoURL: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
          targetRevision: 8.4.2
          path: .
          helm:
            releaseName: kube-state-metrics
            valueFiles:
              - $values/argocd/apps/kube-state-metrics/values.yaml
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/voidlily/kubelab
          targetRevision: HEAD
          ref: values
      destination:
        name: "{{ .name }}"
        namespace: kube-state-metrics
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - CreateNamespace=true
