---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: root-app
spec:
  # TODO make a real project
  project: default

  sources:
    - repoURL: https://github.com/voidlily/kubelab
      targetRevision: HEAD
      # reference root-app
      path: argocd/
    - repoURL: https://github.com/voidlily/kubelab
      targetRevision: HEAD
      # reference all appsets
      path: argocd/appsets/
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
